# Generated by Django 4.0.6 on 2022-07-30 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('marks', models.IntegerField()),
                ('optionA', models.CharField(max_length=300)),
                ('optionB', models.CharField(max_length=300)),
                ('optionC', models.CharField(max_length=300)),
                ('optionD', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Quiz', max_length=50)),
                ('weightage', models.FloatField(verbose_name='Weightage(in %)')),
                ('duration', models.IntegerField(verbose_name='Duration in minutes')),
                ('startafter_time', models.DateTimeField(verbose_name='Start After Time: (format:dd-mm-yyyy HH-MM')),
                ('startbefore_time', models.DateTimeField(verbose_name='Start Before Time: (format:dd-mm-yyyy HH-MM')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('time_taken', models.IntegerField()),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('incorrect_answers', models.PositiveSmallIntegerField()),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
    ]
