# Generated by Django 4.0.6 on 2022-07-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.FloatField()),
                ('duration', models.DurationField()),
                ('startafter_time', models.DateTimeField()),
                ('startbefore_time', models.DateTimeField()),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('marks', models.IntegerField()),
                ('multiple_choice', models.BooleanField()),
                ('optionA', models.CharField(blank=True, max_length=300, null=True)),
                ('optionB', models.CharField(blank=True, max_length=300, null=True)),
                ('optionC', models.CharField(blank=True, max_length=300, null=True)),
                ('optionD', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionbank', to='quizzes.quiz')),
            ],
        ),
    ]
