# Generated by Django 4.0.6 on 2022-07-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='New Quiz', max_length=50),
        ),
    ]
