# Generated by Django 4.0.6 on 2022-07-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='multiple_choice',
        ),
    ]
