# Generated by Django 4.0.6 on 2022-07-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='duration',
        ),
    ]
