# Generated by Django 4.0.6 on 2022-07-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Duration in minutes'),
            preserve_default=False,
        ),
    ]
