# Generated by Django 4.0.6 on 2022-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_question_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
