# Generated by Django 4.0.6 on 2022-07-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_title_quizattempt_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='total_questions',
            new_name='total_marks',
        ),
    ]
