# Generated by Django 4.0.6 on 2022-07-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_rename_total_questions_quizattempt_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionA',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionB',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionC',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionD',
            field=models.CharField(max_length=300),
        ),
    ]
