# Generated by Django 4.0.6 on 2022-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_question_answer_alter_question_optiona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='max_attempts',
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
