# Generated by Django 4.0.6 on 2022-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_quiz_max_attempts_quiz_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(verbose_name='Duration in minutes'),
        ),
    ]
