# Generated by Django 4.0.6 on 2022-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_alter_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='weightage',
            field=models.FloatField(verbose_name='Weightage(in %)'),
        ),
    ]
