# Generated by Django 4.0.6 on 2022-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_quiz_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='startafter_time',
            field=models.DateTimeField(verbose_name='Start After Time: (format:dd-mm-yyyy H-M'),
        ),
    ]
