# Generated by Django 4.0.6 on 2022-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_alter_quiz_startafter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='startafter_time',
            field=models.DateTimeField(verbose_name='Start After Time: (format:dd-mm-yyyy HH-MM'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startbefore_time',
            field=models.DateTimeField(verbose_name='Start Before Time: (format:dd-mm-yyyy HH-MM'),
        ),
    ]
