# Generated by Django 4.0.6 on 2022-07-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_quiz_startafter_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='attempted',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quizzes.quiz'),
        ),
    ]
