# Generated by Django 4.0.6 on 2022-07-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_remove_quiz_attempted_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='quizzes.quiz'),
        ),
    ]
