# Generated by Django 4.0.6 on 2022-07-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
    ]
